/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-surface-variant": "#45464c",
        "surface-container-high": "#e2e8f8",
        "on-surface": "#151c27",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "outline": "#76777d",
        "outline-variant": "#c6c6cd",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#ebf1ff",
        "on-primary-fixed": "#141b2b",
        "secondary-fixed": "#d8e2ff",
        "on-tertiary-fixed": "#07006c",
        "on-secondary-fixed": "#001a42",
        "on-primary-container": "#7d8497",
        "inverse-surface": "#2a313d",
        "secondary-fixed-dim": "#adc6ff",
        "surface-container": "#e7eefe",
        "surface-tint": "#575e70",
        "surface-variant": "#dce2f3",
        "on-primary-fixed-variant": "#404758",
        "inverse-primary": "#c0c6db",
        "tertiary-fixed": "#e1e0ff",
        "surface-container-highest": "#dce2f3",
        "tertiary": "#000000",
        "surface-dim": "#d3daea",
        "on-tertiary-container": "#7073ff",
        "primary-fixed": "#dce2f7",
        "on-error": "#ffffff",
        "on-secondary-container": "#fefcff",
        "on-background": "#151c27",
        "tertiary-fixed-dim": "#c0c1ff",
        "surface-container-low": "#f0f3ff",
        "error": "#ba1a1a",
        "primary-container": "#141b2b",
        "error-container": "#ffdad6",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "surface": "#f9f9ff",
        "background": "#f9f9ff",
        "secondary": "#0058be",
        "on-tertiary": "#ffffff",
        "secondary-container": "#2170e4",
        "tertiary-container": "#07006c",
        "primary-fixed-dim": "#c0c6db",
        "on-secondary": "#ffffff",
        "surface-bright": "#f9f9ff",
        "on-secondary-fixed-variant": "#004395",
        
        // Keep our previous CSS vars too for other pages
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "base": "4px",
        "grid-columns": "12",
        "xl": "32px",
        "md": "16px",
        "grid-gutter": "24px",
        "lg": "24px",
        "2xl": "48px",
        "sm": "8px",
        "xs": "4px",
        "3xl": "64px",
        "grid-margin": "32px"
      },
      "fontFamily": {
        "headline-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "display-xl": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        sans: ['Inter', 'sans-serif'],
      },
      "fontSize": {
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "34px", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "display-xl": ["60px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
