/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1a1c1c",
        "on-surface-variant": "#4c4546",
        "outline-variant": "#cfc4c5",
        "surface-bright": "#f9f9f9",
        "on-secondary-fixed-variant": "#454747",
        "surface-container-highest": "#e2e2e2",
        "inverse-on-surface": "#f1f1f1",
        "surface-variant": "#e2e2e2",
        "tertiary-container": "#241a00",
        "secondary": "#5d5f5f",
        "on-surface": "#1a1c1c",
        "primary-fixed": "#e2e2e2",
        "secondary-container": "#dfe0e0",
        "primary-container": "#1b1b1b",
        "tertiary-fixed": "#ffe088",
        "secondary-fixed-dim": "#c6c6c7",
        "secondary-fixed": "#e2e2e2",
        "surface-container-high": "#e8e8e8",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#574500",
        "surface-tint": "#5e5e5e",
        "primary": "#000000",
        "background": "#f9f9f9",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#474747",
        "surface-container-low": "#f3f3f3",
        "inverse-surface": "#2f3131",
        "tertiary-fixed-dim": "#e9c349",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "tertiary": "#D4AF37",
        "on-secondary-container": "#616363",
        "outline": "#7e7576",
        "surface-container": "#eeeeee",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "on-tertiary-container": "#a08000",
        "surface": "#f9f9f9",
        "on-background": "#1a1c1c",
        "primary-fixed-dim": "#c6c6c6",
        "on-tertiary-fixed": "#241a00",
        "surface-dim": "#dadada",
        "on-primary-container": "#848484",
        "on-primary": "#ffffff",
        "inverse-primary": "#c6c6c6",
        "on-primary-fixed": "#1b1b1b",
        "metallic-gold": "#D4AF37",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-margin": "20px",
        gutter: "16px",
        "section-gap": "64px",
        "element-gap": "12px",
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "button-text": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }],
        "button-text": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
